### ISSUE TITLE
wget: unrecognized option '--show-progress'

### ISSUE THREAD

**Issue by 18445864529** [pswietojanski/slurp#1]
Thank you for releasing this amazing dataset!
But there seems to be a problem with the wget option '--show-progress' in the download script.
I think it may be due to the different wget versions, but I still got this error after updating to the latest version wget-3.2.
I have removed the option and successfully downloaded the dataset anyway, but just pointed it out FYI :-)

**Comment by andreavanzo** [comment]
> Thank you for releasing this amazing dataset!
> But there seems to be a problem with the wget option '--show-progress' in the download script.
> I think it may be due to the different wget versions, but I still got this error after updating to the latest version wget-3.2.
> I have removed the option and successfully downloaded the dataset anyway, but just pointed it out FYI :-)

Thanks for your interest and for reporting this issue!
Yeah, that's probably due to different wget versions. I'm currently on macos 11.0.1, wget-1.21 (I guess it is the latest on osx) and it is working.

We'll fix it anyway. Thanks again.

**Comment by pswietojanski** [comment]
Thanks, disabled this option in cases when it's not available.
