### ISSUE TITLE
Nonexistent audio file.

### ISSUE THREAD

**Issue by 18445864529** [pswietojanski/slurp#2]
In the `train.jsonl` file, the SLURP ID 15302 entry suggests there is a recording called `audio-1434527177-headset.flac`, but I didn't find the corresponding audio file in the slurp_real folder. (The training iteration stopped halfway and threw me this `No such file or directory` error.)

I downloaded the dataset with the provided script, could you kindly check whether this file exists?

**Comment by pswietojanski** [comment]
Thanks for the info. Will check it out over the weekend, for now perhaps ignore it when training.

**Comment by cdqncn** [comment]
Hello, I have improved it.
